name: study_dote
description: StudyDote is the most trusted platform for MD&#x2F;MS entrance examination

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.1
  google_sign_in: ^4.0.1
  shared_preferences: ^0.5.1+1
  http: ^0.12.0+1
  scoped_model: ^1.0.1
  cached_network_image: ^0.6.0+1
  universal_widget: ^1.2.5
  html: ^0.13.4+1
  #progress_dialog: ^1.0.3
  folding_widget: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/first_screen.png
    - assets/google_plus.png
    - assets/facebook.png
    - assets/female_gender.png
    - assets/loader.gif
    - assets/loader_new.gif
    - assets/menu_icons/dailycapsule.png
    - assets/menu_icons/dashboard.png
    - assets/menu_icons/flash.png
    - assets/menu_icons/mockexam.png
    - assets/menu_icons/notice.png
    - assets/menu_icons/practicetest.png
    - assets/menu_icons/reports.png
    - assets/menu_icons/tagged.png
    - assets/menu_icons/timedtest.png
    - assets/menu_icons/badge_question.png
    - assets/menu_icons/badge_answer.png
    - assets/study_dote_fs.png
    - assets/doc_with_tab_fs.png
    - assets/person.png
    - assets/menu_icons/subscribe.png
    - assets/menu_icons/close.png
    - assets/menu_icons/nav_bar_icons/home_white.png
    - assets/menu_icons/nav_bar_icons/qbank.png
    - assets/menu_icons/nav_bar_icons/testseries.png
    - assets/menu_icons/nav_bar_icons/statistics.png
    - assets/drawer_assets/blogs.png
    - assets/drawer_assets/contact.png
    - assets/drawer_assets/dashboard.png
    - assets/drawer_assets/flash_card.png
    - assets/drawer_assets/invite.png
    - assets/drawer_assets/menu.png
    - assets/drawer_assets/mock_exam.png
    - assets/drawer_assets/settings.png
    - assets/drawer_assets/tagged.png
    - assets/drawer_assets/why_us.png
    - assets/why_us/gropu_book.png
    - assets/why_us/tick.png
    - assets/why_us/group_setting.png
    - assets/user_prof_settings/calender.png
    - assets/user_prof_settings/course.png
    - assets/user_prof_settings/email.png
    - assets/user_prof_settings/fullname.png
    - assets/user_prof_settings/institute.png
    - assets/user_prof_settings/password.png
    - assets/user_prof_settings/ph_no.png
    - assets/user_prof_settings/placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
